# Generated by Django 3.2 on 2021-04-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boyband',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('decade', models.TextField(max_length=5)),
                ('albums_sold', models.TextField(max_length=100)),
                ('no_of_members', models.IntegerField()),
            ],
        ),
    ]
