# Generated by Django 3.2 on 2021-04-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='song',
            name='date',
            field=models.DateField(verbose_name='release date'),
        ),
        migrations.AddField(
            model_name='boyband',
            name='awards',
            field=models.ManyToManyField(to='main_app.Award'),
        ),
    ]
